title: My First Github Pages blog
author: Will Walsh
email: will.walsh@outlook.com.au
description: > # this means to ignore newlines until "baseurl:"
  This is my first Github Pages blog. I will be adding random tech tutorials
  and news that I find interesting here.

# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  IronWill79 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
